### ISSUE TITLE
Waiting for heartbeats forever

### ISSUE THREAD

**Issue by rurumi0318** [narthur157/playfab-gsdk-ue4#3]
Hi @narthur157 , I followed [PlayFab instruction](https://docs.microsoft.com/en-us/gaming/playfab/features/multiplayer/servers/locally-debugging-game-servers-and-integration-with-playfab) to setup the local multiplayer agent and tried to integrate your plugin to the agent.

After I ran LocalMultiplayerAgent.exe, PowerShell stucked on "Waiting for heartbeats from the game server" until I manually stopped the dock container.
Since I can't find any UE4 related log files in the output folder which is designated by MultiplayerSettings.json, I can't do further debugging.

In my understanding, when the dedicated server was launched, unreal engine will load your module and execute StartServer automatically, is that correct?

btw how do you debug/log with the LocalMultiplayerAgent? Thanks

**Comment by narthur157** [comment]
StartServer should be called automatically in the GSDK, there's probably a configuration issue in your `MultiplayerSettings.json`

**Comment by rurumi0318** [comment]
I've tried to set the json to process mode and it worked perfectly but failed with container mode
Have you succeeded in container mode?

**Comment by rurumi0318** [comment]
Since this problem may come from PlayFab LocalMultiplayerAgent, i'll close this issue. Thanks, @narthur157 !
